INSERT INTO `produto` (`tipo_produto`, `marca_produto`, `valor_produto`) VALUES

('Alimentos', 'Nestlé', 10.0),
('Móveis', 'IKEA', 10.01),
('Vestuário', 'Nike', 9.99),
('Eletrônico', 'Sony', 9.99),
('Eletrônico', 'Sony', 19.99),
('Vestuário', 'Nike', 9.99),
('Móveis', 'IKEA', 25.51),
('Alimentos', 'Nestlé', 20.01),
('Eletrônico', 'Sony', 19.99),
( 'Vestuário', 'Nike', 9.99),
( 'Móveis', 'IKEA', 19.99),
( 'Alimentos', 'Nestlé', 14.99),
( 'Eletrônico', 'Samsung', 15.99),
( 'Vestuário', 'Adidas', 9.99),
('Móveis', 'Wayfair', 9.04),
('Eletrônico', 'Sony', 38.5),
('Vestuário', 'Nike', 30),
('Eletrônico', 'Sony', 32.4),
('Eletrônico', 'Sony', 25),
('Vestuário', 'Nike', 20),
('Móveis', 'IKEA', 15),
('Alimentos', 'Nestlé', 15),
('Eletrônico', 'Samsung', 20.25),
('Eletrônico', 'Sony', 45.99),
('Eletrônico', 'Sony', 60),
('Vestuário', 'Nike', 60),
('Eletrônico', 'Sony', 15),
('Vestuário', 'Nike', 12),
('Móveis', 'IKEA', 18),
('Alimentos', 'Nestlé', 9.75),
('Eletrônico', 'Sony', 30),
('Vestuário', 'Nike', 25),
('Móveis', 'IKEA', 20),
('Alimentos', 'Nestlé', 25),
('Eletrônico', 'Samsung', 25.75);
